config/routes.rb
Rails.application.routes.draw do

  root 'static#index'
  
  resources :licences
  resources :sites do
    resources :contacts
  end

	get 'use/:id' => 'licences#use', as: :use
	get 'save_licence_to_site/:id/:licence/:site/' => 'licence#save_licence_to_site'

	

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :site
end

app/models/licence.rb
class Licence < ActiveRecord::Base
  has_many :licence_sites
  has_many :sites, through: :licence_sites
end

app/models/licence_site.rb
class LicenceSite < ActiveRecord::Base
  belongs_to :site
  belongs_to :licence
end

app/models/site.rb
class Site < ActiveRecord::Base
  has_many :contacts, dependent: :destroy
  has_many :licence_sites
  has_many :licences, through: :licence_sites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @site = Site.find(params[:site_id])
    @contact = @site.contacts
  end
  
  def show
  end


  def new
    @site = Site.find(params[:site_id])
    @contact = @site.contacts.new(params[:contact])
  end
  
  def create
    @site = Site.find(params[:site_id])
    if @contact = @site.contacts.create(contacts_params) 
      redirect_to site_path(@site)
    else
      render 'new'
    end
  end

  def edit
    @site = Site.find(params[:site_id])
	@contact = @site.contacts.find(params[:id])
  end

  def update
    @site = Site.find(params[:site_id])
	@contact = @site.contacts.find(params[:id])
	if @contact.update(contacts_params)
      redirect_to site_contacts_path(@site)
    else
      render 'edit'
    end
  end
  
  def destroy
		@site = Site.find(params[:site_id])
		@contact = @site.contacts.find(params[:id])
		@contact.destroy
		redirect_to site_contacts_path(@site)
  end
  
  private
  
  def contacts_params
    params.require(:contact).permit(:name, :company, :telephone, :email)
  end
  
end

app/controllers/licences_controller.rb
class LicencesController < ApplicationController
  def index
    @licences = Licence.all
  end

	def use
		@sites = Site.all
		@licence = Licence.find(params[:id])
	end

	def save_licence_to_site

		site = params[:site]
		licence = params[:licence]

		find_site_for_licence = LicenceSite.new(site_id: site, licence_id: licence)
		redirect_to site_path(site)
	end

  def show
    @licence = Licence.find(params[:id])
  end

  def new
    @licence = Licence.new
  end
  
  def create
    @licence = Licence.new(licence_params)
    if @licence.save
      redirect_to @licence
    else
      render 'new'
    end
    
  end

  def edit
    @licence = Licence.find(params[:id])
  end  
  
  def update
    @licence = Licence.find(params[:id])
    
    if @licence.update(licence_params)
      redirect_to @licence
    else
      render 'edit'
    end
  end
  
  def destroy
    @licence = Licence.find(params[:id])
    @licence.destroy
    redirect_to licences_path
  end
  
  
  private
  
  def licence_params
    params.require(:licence).permit(:name, :type_of_licence, :date, :quantity, :web_site_of_purchase, :company_of_purchase, :price)
    
  end
  
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
    @site = Site.new
  end
  
  def create
    @site = Site.new(site_params)
    if @site.save
      redirect_to @site
    else
      render 'new'
    end
  end

  def edit
    @site = Site.find(params[:id])
  end
  
  def update
    @site = Site.find(params[:id])
    if @site.update(site_params)
      redirect_to @site
    else
      render 'edit'
    end
  end
  
  def destroy
    @site = Site.find(params[:id])
    @site.destroy
    redirect_to sites_path
  end
  
  private
  
  def site_params
    params.require(:site).permit(:company, :url, :type_of_site, :user_name_site, :password_site, :gmail_of_site, :gmail_password, :dropbox_password)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/licences_helper.rb
module LicencesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/contacts/_form.html.erb
<div class="centers-forms">
  <%= bootstrap_form_for [ @site, @contact ] do |f| %>
      <%= f.text_field :name %>
      <%= f.text_field :company %>
      <%= f.text_field :telephone %>
      <%= f.text_field :email %>
      
      <%= f.submit "Save", class: "btn btn-success" %>
  <% end %>

app/views/contacts/edit.html.erb
<h1 class="text-center">Edit contact</h1>

<%= render 'form' %>

</div>

app/views/contacts/index.html.erb
<div class="text-center">
  <%= link_to "Add new contact", new_site_contact_path(@site), class: 'btn btn-success' %>
</div>
<br>

<h2 class="text-center">All contacts for <%= @site.company %></h2>

<% if @contact.empty? %>
  <p> there seem not to be any contasts for <%= @site.company %></p>
<% else %>
  <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Company</th>
            <th>Telephone</th>
            <th>email</th>
          </tr>
        </thead>
        <tbody>
          <% current_number = 1 %>
          <% @contact.each do |contact| %>
            <tr>
              <% # it just counts from 1 up %>
              <td><%= current_number %></td>
              <% current_number = current_number + 1 %>

    <td><%= contact.name %></td>
    <td><%= contact.company %></td>
    <td><%= contact.telephone %></td>
    <td><%= contact.email %></td>

    <td><%= link_to 'edit', edit_site_contact_path(@site, contact), class: 'btn btn-default'  %></td>
    <td><%= link_to 'delete', site_contact_path(@site, contact), method: :delete, data: { confirm: 'are you shuro you want to delete this contact?' }, class: 'btn btn-default'  %></td>
            </tr>

          <% end %>
        </tbody>
      </table>
<% end %>

app/views/contacts/new.html.erb
<h1 class="text-center">Add new contact</h1>
<h3 class="text-center">for this website or app</h3>

<%= render 'form' %>

</div>

app/views/contacts/show.html.erb
<h1>Contacts#show</h1>
<p>Find me in app/views/contacts/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LicenceApp</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <a href="/">
      <h1 class="text-center">Licence Book</h1>
      <h4 class="text-center headding-front-page">app for licences & contacts</h4>
    </a>
    <%= yield %>
  </div>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>
</html>

app/views/licences/_form.html.erb
<div class="centers-forms">
    <%= bootstrap_form_for @licence do |f| %>
      <%= f.text_field :name, label: 'Description' %>
      <%= f.select :type_of_licence, [ 'picture', 'video', 'code' ] %>
      <%= f.date_field :date %>
      <%= f.select :quantity, [['1', 1], ['2', 2], ['3', 3], ['4', 4], ['5', 5], ['unlimited', 1000000]] %>
      <%= f.text_field :web_site_of_purchase %>
      <%= f.text_field :company_of_purchase %>
      <%= f.number_field :price %>
      
  <%= f.submit "Save", class: "btn btn-success" %>
  <% end %>

app/views/licences/edit.html.erb
<h1 class="text-center">Edit licence</h1>

<%= render 'form' %>

</div>

app/views/licences/index.html.erb
<div class="text-center">
  <%= link_to "Add new licence", new_licence_path, class: 'btn btn-success' %>
</div>
<br>

<h2 class="text-center">All licences</h2>

<% if @licences.empty? %>
  <p>There seem not to be any licences in the database</p>
<% else %>
  <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Type</th>
            <th>Date</th>
            <th>Quantity</th>
            <th>Web site of purchase</th>
            <th>Company of purchase</th>
            <th>Price</th>
          </tr>
        </thead>
        <tbody>
          <% current_number = 1 %>
          <% @licences.each do |licence| %>
            <tr>
              <% # it just counts from 1 up %>
              <td><%= current_number %></td>
              <% current_number = current_number + 1 %>
              
              <td><%= licence.name %></td>
              <td><%= licence.type_of_licence %></td>
              <td><%= licence.date %></td>
              <td><%= licence.quantity %></td>
              <td><%= licence.web_site_of_purchase %></td>
              <td><%= licence.company_of_purchase %></td>
              <td><%= number_to_currency(licence.price, unit: "€", separator: ",", delimiter: "", format: "%n %u") %></td>
							<% if licence.quantity > 0 %>
								<td><%= link_to 'Use it', use_path(licence), class: 'btn btn-default'  %></td>

							<% end %>
              <td><%= link_to 'Edit', edit_licence_path(licence), class: 'btn btn-default'  %></td>
              <td><%= link_to 'Delete', licence_path(licence), method: :delete, data: { confirm: 'Are you shuro you want to delete this licence?' }, class: 'btn btn-default'  %></td>
            </tr>
            
          <% end %>
        </tbody>
      </table>
<% end %>

app/views/licences/new.html.erb
<h1 class="text-center">Add new licence</h1>

<%= render 'form' %>

</div>

app/views/licences/show.html.erb
<div class="text-center">

  <h1>Licence for <%= @licence.name %></h1><br>

  <h4>Name or description</h4>
  <p><%= @licence.name %></p><br>

  <h4>Type data</h4>
  <p><%= @licence.type_of_licence %></p><br>
    
  <h4>Date of purtchase</h4>
  <p><%= @licence.date %></p><br>
  
  <h4>Quantity</h4>
  <p><%= @licence.quantity %></p><br>

  <h4>Website of purchase</h4>
  <p><%= @licence.web_site_of_purchase %></p><br>
  
  <h4>Company of purchase</h4>
  <p><%= @licence.company_of_purchase %></p><br>
  
  <h4>Paid price in Euros</h4>
  <p><%= @licence.price %></p><br>
  
  
  <br>
  
  <%= link_to 'Go to all licences', licences_path, class: 'btn btn-lg btn-primary' %>

  <br>
  <br> 
  <%= link_to 'Edit this   licences', edit_licence_path(@licence), class: 'btn btn-default' %>
  
  <br>
  <br>


</div>

app/views/licences/use.html.erb
<%= @licence.name %> <br>
<%= @licence.id %> <br>
quantity:
<%= @licence.quantity %> 

<% if @sites.empty? %>
  <p> There seem not to be any websites or apps in the database </p>
<% else %>
  <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Company</th>
            <th>url</th>
          </tr>
        </thead>
        <tbody>
          <% current_number = 1 %>
          <% @sites.each do |site| %>
            <tr>
              <% # it just counts from 1 up %>
              <td><%= current_number %></td>
              <% current_number = current_number + 1 %>
              
    <td><%= site.company %></td>
    <td><%= site.url %></td>
    
		<td><%= link_to 'Apply this licence on this app', { action: :save_licence_to_site, id: site[:id], licence: @licence[:id], site: site[:id] }, class: 'btn btn-default'  %></td>
            </tr>
            
          <% end %>
        </tbody>
      </table>
<% end %>

app/views/sites/_form.html.erb
<div class="centers-forms">
  <%= bootstrap_form_for @site do |f| %>
      <%= f.text_field :company %>
      <%= f.text_field :url %>
      <%= f.select :type_of_site, [ 'website', 'webstore', 'application' ], label: 'Type' %>
      <%= f.text_field :user_name_site %>
      <%= f.text_field :password_site %>
      <%= f.text_field :gmail_of_site %>
      <%= f.text_field :gmail_password %>
      <%= f.text_field :dropbox_password %>  
      <%= f.submit "Save", class: "btn btn-success" %>
  <% end %>

app/views/sites/edit.html.erb
<h1 class="text-center">Add new website or app</h1>

<%= render 'form' %>

</div>

app/views/sites/index.html.erb
<div class="text-center">
  <%= link_to "Add new website or app", new_site_path, class: 'btn btn-success' %>
</div>
<br>

<h2 class="text-center">All websites & apps</h2>

<% if @sites.empty? %>
  <p> There seem not to be any websites or apps in the database </p>
<% else %>
  <table class="table table-striped">
        <thead>
          <tr>
            <th>#</th>
            <th>Company</th>
            <th>url</th>
            <th>Type</th>
            <th>User name</th>
            <th>Password</th>
            <th>Gmail</th>
            <th>Gmail password</th>
            <th>Dropbox password</th>
          </tr>
        </thead>
        <tbody>
          <% current_number = 1 %>
          <% @sites.each do |site| %>
            <tr>
              <% # it just counts from 1 up %>
              <td><%= current_number %></td>
              <% current_number = current_number + 1 %>
              
    <td><%= site.company %></td>
    <td><%= site.url %></td>
    <td><%= site.type_of_site %></td>
    <td><%= site.user_name_site %></td>
    <td><%= site.password_site %></td>
    <td><%= site.gmail_of_site %></td>
    <td><%= site.gmail_password %></td>
    <td><%= site.dropbox_password %></td>
    
    <td><%= link_to 'Edit', edit_site_path(site), class: 'btn btn-default'  %></td>
    <td><%= link_to 'Delete', site_path(site), method: :delete, data: { confirm: 'Are you shuro you want to delete this site?' }, class: 'btn btn-default'  %></td>
    <td><%= link_to 'new contact', new_site_contact_path(site), class: 'btn btn-default' %></td>
    <td><%= link_to 'all contact', site_contacts_path(site), class: 'btn btn-default' %></td>
            </tr>
            
          <% end %>
        </tbody>
      </table>
<% end %>

app/views/sites/new.html.erb
<h1 class="text-center">Add new website or app</h1>

<%= render 'form' %>

</div>

app/views/sites/show.html.erb
<div class="text-center">

  <h1><%= @site.type_of_site %> for <%= @site.company %></h1><br>

  <h4>Company</h4>
  <p><%= @site.company %></p><br>
  
  <h4>Url</h4>
  <p><%= @site.url %></p><br>
  
  <h4>Type</h4>
  <p><%= @site.type_of_site %></p><br>
  
  <h4>User name or admin</h4>
  <p><%= @site.user_name_site %></p><br>
  
  <h4>password for the <%= @site.type_of_site %></h4>
  <p><%= @site.password_site %></p><br>
  
  <h4>Gmail</h4>
  <p><%= @site.gmail_of_site %></p><br>
  
  <h4>Gmail passowrd</h4>
  <p><%= @site.gmail_password %></p><br>
  
  <h4>dropbox password</h4>
  <p><%= @site.dropbox_password %></p><br>

    <br>
  
  <%= link_to 'Go to all websites & apps ', sites_path, class: 'btn btn-lg btn-primary' %>

  <br>
  <br> 
  <%= link_to 'Edit this ', edit_site_path(@site), class: 'btn btn-default' %>
  
  <br>
  <br>





</div>